# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicPlay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicPlay
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'MusicPlayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicPlayUITests' do
    # Pods for testing
  end

end
